# Generated by Django 5.1.1 on 2024-09-19 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=50, unique=True)),
                ('municipality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ica_registration', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('application_frequency', models.IntegerField(help_text='Frequency in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_application_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FungusControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ica_registration', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('application_frequency', models.IntegerField(help_text='Frequency in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_period', models.IntegerField(help_text='Withdrawal period in days')),
                ('fungus_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ica_registration', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('application_frequency', models.IntegerField(help_text='Frequency in days')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdrawal_period', models.IntegerField(help_text='Withdrawal period in days')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseries', to='nurseryapp.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='nurseryapp.producer'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nurseryapp.nursery')),
            ],
        ),
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('application_date', models.DateField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='nurseryapp.task')),
            ],
        ),
    ]
